name: Publish

on:
  create:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install --only=dev
      - run: npm run api
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: "gen/package.json"
          token: ${{ secrets.NPM_TOKEN }}
